version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "7001:7001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 7001 --reload
